name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 1. 시스템 nginx 중지 (도커 nginx와 포트 충돌 방지)
            sudo systemctl stop nginx 2>/dev/null || true
            sudo systemctl disable nginx 2>/dev/null || true

            # 2. 프로젝트 폴더로 이동 또는 클론
            if [ ! -d "/home/ubuntu/interview-platform" ]; then
                git clone https://github.com/${{ secrets.REPO_OWNER }}/${{ secrets.REPO_NAME }} /home/ubuntu/interview-platform
            fi
            cd /home/ubuntu/interview-platform

            # 3. Git 리셋 후 최신 코드 가져오기
            git reset --hard HEAD
            git pull origin main

            # 4. .env 파일 반영 (정확한 경로 지정)
            echo "${{ secrets.ENV_FILE_ROOT }}" > /home/ubuntu/interview-platform/.env
            echo "${{ secrets.ENV_FILE_FRONT }}" > /home/ubuntu/interview-platform/frontend/.env

            # 5. Docker 클린 배포
            docker-compose down || true
            docker network rm interview-platform_default 2>/dev/null || true
            docker network prune -f
            docker-compose pull
            docker system prune -a --volumes -f
            docker-compose build --no-cache
            docker-compose up -d

            # 6. 이미지 정리
            docker image prune -f
