name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 1. 시스템 nginx 중지 (도커 nginx와 포트 충돌 방지)
            sudo systemctl stop nginx || true
            sudo systemctl disable nginx || true

            # 2. 프로젝트 폴더로 이동 또는 클론
            if [ ! -d "~/interview-platform" ]; then
                git clone https://github.com/${{ secrets.REPO_OWNER }}/${{ secrets.REPO_NAME }} ~/interview-platform
            else
                cd ~/interview-platform
                git reset --hard HEAD
                git pull origin main
            fi

            # 3. 최신 코드 가져오기
            git pull origin main

            # 4. .env 파일 반영
            echo "${{ secrets.ENV_FILE_ROOT }}" > .env
            echo "${{ secrets.ENV_FILE_FRONT }}" > ./frontend/.env

            # 5. Docker 클린 배포
            docker-compose down
            docker-compose pull
            docker system prune -a --volumes -f
            docker-compose build --no-cache
            docker-compose up -d

            # 6. 이미지 정리
            docker image prune -f
