name: Deploy to EC2

on:
  push:
    branches: [main] # 혹은 배포 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # EC2 접속 후 명령어 실행
            cd ~/interview-platform || git clone https://github.com/<your-id>/<your-repo>.git ~/interview-platform
            cd ~/interview-platform

            # 최신 코드 반영
            git pull origin main

            # 환경 변수 작성 (최초 1회만 수동 작성해놓는 것도 가능)
            echo "${{ secrets.ENV_FILE }}" > .env

            # 컨테이너 재빌드 및 실행
            docker-compose down
            docker-compose pull
            docker-compose up -d --build

            docker image prune -f
